Controllers/ExamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Simulacao.Data;
using Simulacao.Models;

namespace Simulacao.Controllers{
    public class ExamController : Controller {
        private ApplicationDbContext dbContext;
        private readonly Configuracoes _configuracoes;
        public ExamController(IOptions<Configuracoes> configuracoes) {
            _configuracoes = configuracoes.Value;
            dbContext = ApplicationDbContextFactory.Create();
        }
        private async Task<SimuladoViewModel> selecionaPerguntas(int? page) {
            SimuladoViewModel svm = new SimuladoViewModel();
            svm.Questoes = await PaginatedList<Questao>.CreateAsync(SimuladoViewModel.listaQuestoes, page ?? 1, 1);
            svm.RespostasQuestao = dbContext.Resposta.Where(r => r.idQuestao == svm.Questoes.First().idQuestao).ToList();
            foreach (var resposta in svm.RespostasQuestao) {
                if (resposta.Correta == true) {
                    ViewData["idRespostaCorreta"] = resposta.idResposta;
                }
            }
            return svm;
        }
        [Authorize(Roles = "Admin, Exam")]
        public async Task<ActionResult> Simulacao(int? page, long idCourse) {
            List<Area> areas = dbContext.Area.Where(a => a.idCourse == idCourse).ToList();
            var idsArea = new long[areas.Count()];
            int i = 0;
            foreach (var area in areas) {
                idsArea.SetValue(area.idArea, i);
                i++;
            }
            var random = new Random();
            var questoesArea = (from q in dbContext.Questao where idsArea.Contains(q.idArea) orderby random.Next() select q).Take(_configuracoes.NumeroQuestoesExame);
            if (questoesArea.Count() != 0) {
                //Grava temporariamente as 80 questões do simulado
                SimuladoViewModel.listaQuestoes = questoesArea;
                SimuladoViewModel svm = await selecionaPerguntas(page);
                ViewData["segundos"] = 0;
                return View("Index", svm);
            }
            return RedirectToRoute(new {
                Controller = "Enrollment",
                Action = "Index"
            });
        }
        public async Task<ActionResult> SimulacaoStep(int? page, int segundos) {
            //Seleciona a nova pergunta que irá mostrar para o usuário
            SimuladoViewModel svm = await selecionaPerguntas(page);
            ViewData["segundos"] = segundos;
            return View("Index", svm);
        }
        public ActionResult FinalizarSimulado(int questoesAcertadas, string tempoFinalizado) {
            ViewData["questoesAcertadas"] = questoesAcertadas;
            ViewData["totalQuestoes"] = _configuracoes.NumeroQuestoesSimulado;
            float tempo = Convert.ToInt32(tempoFinalizado);
            if (tempo <= 60) {
                ViewData["tempoFinalizado"] = tempoFinalizado + " seconds";
            } else {
                tempo = tempo / 60;
                int minutos = Convert.ToInt32(tempo);
                if (minutos > tempo) {
                    minutos--;
                }
                int segundos = Convert.ToInt32((tempo - minutos) * 60);
                ViewData["tempoFinalizado"] = minutos + " minute(s) e " + segundos + " seconds";
            }
            return View("FinalizarExam");
        }
    }
}

Views/Shared/_CourseSteps.cshtml
@model StepCourseViewModel

@{
    var nextDisabled = !Model.Subareas.HasNextPage ? "display: none;" : "";
    var previousDisabled = !Model.Subareas.HasPreviousPage ? "display: none;" : "";

    <script>
        function mudarPagina(idCourse, pagina) {
            document.getElementById("page").setAttribute("value", pagina);
            document.getElementById("idCourse").setAttribute("value", idCourse);
        }
    </script>
}
@using (Html.BeginForm("Course", "Enrollment", FormMethod.Post, new { @class = "tab-wizard wizard-circle", role = "form" })) {
    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <input id="previous" onclick="mudarPagina(@Model.Course.idCourse, @(Model.Subareas.PageIndex - 1))" class="btn btn-info" style="@previousDisabled" type="submit" value="Previous"/>
            <input id="proximo" onclick="mudarPagina(@Model.Course.idCourse, @(Model.Subareas.PageIndex + 1))" class="btn btn-info" style="@nextDisabled" type="submit" value="Next"/>
        </div>
        <div class="col-md-7 align-self-center">
            <div class="d-flex justify-content-end align-items-center">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">@Html.ActionLink(@Model.Area.NomeArea, "StartCourse", "Enrollment", new {idCourse = @Model.Course.idCourse})</li>
                    <li class="breadcrumb-item active">@Model.Subareas[0].NomeSubarea</li>
                </ol>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="card">
                @Html.Hidden("page")
                @Html.Hidden("idCourse")
                <ul class="nav nav-tabs customtab" role="tablist">
                    @foreach (var material in @Model.StudyMaterials) {                        
                        if (material.idMaterialEstudo == @Model.StudyMaterials.First().idMaterialEstudo) {
                            <li class="nav-item"> <a class="nav-link active" data-toggle="tab" href="#@material.idMaterialEstudo" role="tab"><span class="hidden-sm-up"><i class="ti-book" data-toggle="tooltip" title="@material.Titulo"></i></span> <span class="hidden-xs-down"></span></a> </li>
                        } else {
                            <li class="nav-item"> <a class="nav-link" data-toggle="tab" href="#@material.idMaterialEstudo" role="tab"><span class="hidden-sm-up"><i class="ti-book" data-toggle="tooltip" title="@material.Titulo"></i></span> <span class="hidden-xs-down"></span></a> </li>
                        }
                    }
                </ul>
                <!-- Tab panes -->
                <div class="tab-content">
                    @foreach (var material in @Model.StudyMaterials) {
                        if (material.idMaterialEstudo == @Model.StudyMaterials.First().idMaterialEstudo) {
                            <div class="tab-pane active" id="@material.idMaterialEstudo" role="tabpanel">
                                <div class="p-20">
                                    @Html.Raw(@material.DescricaoConteudo)
                                </div>
                            </div>
                        } else {
                            <div class="tab-pane" id="@material.idMaterialEstudo" role="tabpanel">
                                <div class="p-20">
                                    @Html.Raw(@material.DescricaoConteudo)
                                </div>
                            </div>
                        }
                    }
                </div>
            </div>
        </div>
    </div>
}

Views/Shared/_CoursesPartial.cshtml
@model List<CourseViewModel>

@inject SignInManager<ApplicationUser> SignInManager

@if (SignInManager.IsSignedIn(User)) {
<div class="row">
	@foreach (var course in this.Model) {
		<div class="col-md-3">
			<img class="img-responsive" alt="user" src="@course.imgSrc">
			<div class="card">
				<div class="card-body">
					<h5 class="card-title">@course.CourseName</h5>
					<div class="d-flex no-block align-items-center">
						<span><i class="ti-alarm-clock"></i> Price: @course.Price</span>
					</div>
					<div class="d-flex no-block align-items-center p-t-10">
						<span><i class="ti-user"></i> Professor Name: @course.ProfessorName</span>
					</div>
					@Html.ActionLink("More Details", "CourseInfo", "Course", new {idCourse = @course.idCourse}, new { @class="btn btn-success btn-rounded waves-effect waves-light m-t-30"})
				</div>
			</div>
		</div>
	}
</div>
} else {
<div class="courses">
	<div class="courses_background"></div>
	<div class="container">
		@if((string)@ViewData["Controller"] == "1") {
		<div class="row">
			<div class="col">
				<h2 class="section_title text-center">Online Courses</h2>
			</div>
		</div>
		}
		<div class="row courses_row">
			<!-- Course -->
			<div class="col-lg-4 course_col">
				<div class="course">
					<div class="course_image"><img src="../lingua/images/forklift-835340.jpg" alt="" style="width:100%; height:180px;"></div>
					<div class="course_body">
						<div class="course_title">@Html.ActionLink("Inventory Management", "GestaoEstoques", "Home", new {idArea = 3})</div>
						<div class="course_info">
							<ul>
								<li><a href="#">Otacilio</a></li>
							</ul>
						</div>
						<div class="course_text">
							<p>Inventory management is all about having the right inventory at the right quantity, in the right place, at the right time, and at the right cost. But how do you implement the best inventory management techniques to ensure the best results?</p>
						</div>
					</div>
					<div class="course_footer d-flex flex-row align-items-center justify-content-start">
						<div class="course_students"><i class="fa fa-user" aria-hidden="true"></i><span>10</span></div>
						<div class="course_rating ml-auto"><i class="fa fa-star" aria-hidden="true"></i><span>4,5</span></div>
						<div class="course_mark course_free trans_200"><a asp-area="" asp-controller="Account" asp-action="Login">Free</a></div>
					</div>
				</div>
			</div>

			<!-- Course -->
			<div class="col-lg-4 course_col">
				<div class="course">
					<div class="course_image"><img src="../lingua/images/logistics-3125131.jpg" alt="" style="width:100%; height:180px;"></div>
					<div class="course_body">
						<div class="course_title">@Html.ActionLink("Logistics and Supply Chain Management", "GestaoEstoques", "Home", new {idArea = 2})</div>
						<div class="course_info">
							<ul>
								<li><a href="#">Otacilio</a></li>
							</ul>
						</div>
						<div class="course_text">
							<p>Is Logistics the Same as Supply Chain Management?</p>
						</div>
					</div>
					<div class="course_footer d-flex flex-row align-items-center justify-content-start">
						<div class="course_students"><i class="fa fa-user" aria-hidden="true"></i><span>10</span></div>
						<div class="course_rating ml-auto"><i class="fa fa-star" aria-hidden="true"></i><span>4,5</span></div>
						<div class="course_mark course_free trans_200"><a asp-area="" asp-controller="Account" asp-action="Login">Free</a></div>
					</div>
				</div>
			</div>

			<!-- Course -->
			<div class="col-lg-4 course_col">
				<div class="course">
					<div class="course_image"><img src="../lingua/images/industry-2633878.jpg" alt="" style="width:100%; height:180px;"></div>
					<div class="course_body">
						<div class="course_title">@Html.ActionLink("Organizational Learning", "GestaoEstoques", "Home", new {idArea = 1})</div>
						<div class="course_info">
							<ul>
								<li><a href="#">Martius Rodriguez</a></li>
							</ul>
						</div>
						<div class="course_text">
							<p>Is the process of creating, retaining, and transferring knowledge within an organization.</p>
						</div>
					</div>
					<div class="course_footer d-flex flex-row align-items-center justify-content-start">
						<div class="course_students"><i class="fa fa-user" aria-hidden="true"></i><span>10</span></div>
						<div class="course_rating ml-auto"><i class="fa fa-star" aria-hidden="true"></i><span>4,5</span></div>
						<div class="course_mark trans_200"><a asp-area="" asp-controller="Account" asp-action="Login">$45</a></div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
}

Views/Shared/_EventsPartial.cshtml
<div class="events">
		<div class="container">
			<div class="row">
				<div class="col">
					<h2 class="section_title text-center">Upcoming Events</h2>
				</div>
			</div>
			<div class="row events_row">
				
				<!-- Event -->
				<div class="col-lg-4 event_col">
					<div class="event">
						<div class="event_image"><img src="lingua/images/event_1.jpg" alt=""></div>
						<div class="event_date d-flex flex-column align-items-center justify-content-center">
							<div class="event_day">26</div>
							<div class="event_month">aug</div>
						</div>
						<div class="event_body d-flex flex-row align-items-center justify-content-start">
							<div class="event_title"><a href="#">Networking Day</a></div>
							<div class="event_tag ml-auto">Free</div>
						</div>
					</div>
				</div>

				<!-- Event -->
				<div class="col-lg-4 event_col">
					<div class="event">
						<div class="event_image"><img src="lingua/images/event_2.jpg" alt=""></div>
						<div class="event_date d-flex flex-column align-items-center justify-content-center">
							<div class="event_day">26</div>
							<div class="event_month">aug</div>
						</div>
						<div class="event_body d-flex flex-row align-items-center justify-content-start">
							<div class="event_title"><a href="#">Networking Day</a></div>
							<div class="event_tag ml-auto">Free</div>
						</div>
					</div>
				</div>

				<!-- Event -->
				<div class="col-lg-4 event_col">
					<div class="event">
						<div class="event_image"><img src="lingua/images/event_3.jpg" alt=""></div>
						<div class="event_date d-flex flex-column align-items-center justify-content-center">
							<div class="event_day">26</div>
							<div class="event_month">aug</div>
						</div>
						<div class="event_body d-flex flex-row align-items-center justify-content-start">
							<div class="event_title"><a href="#">Networking Day</a></div>
							<div class="event_tag ml-auto">Free</div>
						</div>
					</div>
				</div>

			</div>
		</div>
	</div>

Views/Shared/_ForumPartial.cshtml
<div class="col-lg-6">
	<div class="card">
		<div class="card-body">
			<h5 class="card-title">Recent Comments</h5>
		</div>
		<!-- ============================================================== -->
		<!-- Comment widgets -->
		<!-- ============================================================== -->
		<div class="comment-widgets">
			<!-- Comment Row -->
			<div class="d-flex no-block comment-row">
				<div class="p-2"><span class="round"><img src="../assets/images/users/1.jpg" alt="user" width="50"></span></div>
				<div class="comment-text w-100">
					<h5 class="font-medium">James Anderson</h5>
					<p class="m-b-10 text-muted">Lorem Ipsum is simply dummy text of the printing and type setting industry. Lorem Ipsum has beenorem Ipsum is simply dummy text of the printing and type setting industry.</p>
					<div class="comment-footer">
						<span class="text-muted pull-right">April 14, 2016</span> <span class="badge badge-pill badge-info">Pending</span> <span class="action-icons">
								<a href="javascript:void(0)"><i class="ti-pencil-alt"></i></a>
								<a href="javascript:void(0)"><i class="ti-check"></i></a>
								<a href="javascript:void(0)"><i class="ti-heart"></i></a>    
							</span>
					</div>
				</div>
			</div>
			<!-- Comment Row -->
			<div class="d-flex no-block comment-row border-top">
				<div class="p-2"><span class="round"><img src="../assets/images/users/2.jpg" alt="user" width="50"></span></div>
				<div class="comment-text active w-100">
					<h5 class="font-medium">Michael Jorden</h5>
					<p class="m-b-10 text-muted">Lorem Ipsum is simply dummy text of the printing and type setting industry. Lorem Ipsum has beenorem Ipsum is simply dummy text of the printing and type setting industry..</p>
					<div class="comment-footer">
						<span class="text-muted pull-right">April 14, 2016</span>
						<span class="badge badge-pill badge-success">Approved</span>
						<span class="action-icons active">
								<a href="javascript:void(0)"><i class="ti-pencil-alt"></i></a>
								<a href="javascript:void(0)"><i class="icon-close"></i></a>
								<a href="javascript:void(0)"><i class="ti-heart text-danger"></i></a>    
							</span>
					</div>
				</div>
			</div>
			<!-- Comment Row -->
			<div class="d-flex no-block comment-row border-top">
				<div class="p-2"><span class="round"><img src="../assets/images/users/3.jpg" alt="user" width="50"></span></div>
				<div class="comment-text w-100">
					<h5 class="font-medium">Johnathan Doeting</h5>
					<p class="m-b-10 text-muted">Lorem Ipsum is simply dummy text of the printing and type setting industry. Lorem Ipsum has beenorem Ipsum is simply dummy text of the printing and type setting industry.</p>
					<div class="comment-footer">
						<span class="text-muted pull-right">April 14, 2016</span>
						<span class="badge badge-pill badge-danger">Rejected</span>
						<span class="action-icons">
								<a href="javascript:void(0)"><i class="ti-pencil-alt"></i></a>
								<a href="javascript:void(0)"><i class="ti-check"></i></a>
								<a href="javascript:void(0)"><i class="ti-heart"></i></a>    
							</span>
					</div>
				</div>
			</div>
			<!-- Comment Row -->
			<div class="d-flex no-block comment-row border-top">
				<div class="p-2"><span class="round"><img src="../assets/images/users/4.jpg" alt="user" width="50"></span></div>
				<div class="comment-text active w-100">
					<h5 class="font-medium">Genelia doe</h5>
					<p class="m-b-10 text-muted">Lorem Ipsum is simply dummy text of the printing and type setting industry. Lorem Ipsum has beenorem Ipsum is simply dummy text of the printing and type setting industry..</p>
					<div class="comment-footer">
						<span class="text-muted pull-right">April 14, 2016</span>
						<span class="badge badge-pill badge-success">Approved</span>
						<span class="action-icons active">
								<a href="javascript:void(0)"><i class="ti-pencil-alt"></i></a>
								<a href="javascript:void(0)"><i class="icon-close"></i></a>
								<a href="javascript:void(0)"><i class="ti-heart text-danger"></i></a>    
							</span>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

Views/Shared/_LeftSideBarNavigation.cshtml
<aside class="left-sidebar">
    <!-- Sidebar scroll-->
    <div class="scroll-sidebar">
        <!-- Sidebar navigation-->
        <nav class="sidebar-nav">
            <ul id="sidebarnav">
                <li class="nav-small-cap">--- @ViewData["CourseName"]</li>
                <li><a class="waves-effect waves-dark" href="@Url.Action("StartCourse", "Enrollment", new {idCourse = @ViewData["idCourse"]})"><i class="fa fa-bars"></i><span class="hide-menu">Course</span></a></li>
                <li><a class="waves-effect waves-dark" href="@Url.Action("Discussion", "Enrollment", new {idCourse = @ViewData["idCourse"]})"><i class="ti-layout-media-right-alt"></i><span class="hide-menu">Discussion</span></a></li>
            </ul>
        </nav>
        <!-- End Sidebar navigation -->
    </div>
    <!-- End Sidebar scroll-->
</aside>

Views/Shared/_MyCoursesPartial.cshtml
@model EnrollmentViewModel

<div class="row">
    @foreach (var course in this.Model.Courses) {
        <div class="col-md-3">
            <img class="img-responsive" alt="user" src="@course.imgSrc">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">@course.CourseName</h5>
                    <div class="d-flex no-block align-items-center">
                        <span><i class="ti-money"></i> Price: @course.Price</span>
                    </div>
                    <div class="d-flex no-block align-items-center p-t-10">
                        <span><i class="ti-user"></i> Professor Name: @course.ProfessorName</span>
                    </div>
                    @Html.ActionLink("Start Course", "StartCourse", "Enrollment", new {idCourse = @course.idCourse}, new { @class="btn btn-success btn-rounded waves-effect waves-light m-t-30"})
                    @Html.ActionLink("Unenroll", "Unenroll", "Enrollment", new {idCourse = @course.idCourse}, new { @class="btn btn-danger btn-rounded waves-effect waves-light m-t-30", @onclick="return confirm('Are you sure you want to unenroll from course?');"})
                </div>
            </div>
        </div>
    }
</div>

Views/Shared/_MyExams.cshtml
@model EnrollmentViewModel

<div class="row">
    @foreach (var course in this.Model.Courses) {
        <div class="col-md-3">
            <img class="img-responsive" alt="user" src="@course.imgSrc">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">@course.CourseName</h5>
                    <div class="d-flex no-block align-items-center">
                        <span><i class="ti-money"></i> Price: @course.Price</span>
                    </div>
                    <div class="d-flex no-block align-items-center p-t-10">
                        <span><i class="ti-user"></i> Professor Name: @course.ProfessorName</span>
                    </div>
                    @Html.ActionLink("Start Exam", "Simulacao", "Exam", new {idCourse = @course.idCourse}, new { @class="btn btn-success btn-rounded waves-effect waves-light m-t-30"})
                </div>
            </div>
        </div>
    }
</div>

Views/Shared/_MySimulateds.cshtml
@model EnrollmentViewModel

<div class="row">
    @foreach (var course in this.Model.Courses) {
        <div class="col-md-3">
            <img class="img-responsive" alt="user" src="@course.imgSrc">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">@course.CourseName</h5>
                    <div class="d-flex no-block align-items-center">
                        <span><i class="ti-money"></i> Price: @course.Price</span>
                    </div>
                    <div class="d-flex no-block align-items-center p-t-10">
                        <span><i class="ti-user"></i> Professor Name: @course.ProfessorName</span>
                    </div>
                    @Html.ActionLink("Start Simulation", "Simulacao", "Simulacao", new {idCourse = @course.idCourse}, new { @class="btn btn-success btn-rounded waves-effect waves-light m-t-30"})
                </div>
            </div>
        </div>
    }
</div>

Views/Shared/_StatusMessage.cshtml
@model string

@if (!String.IsNullOrEmpty(Model))
{
    var statusMessageClass = Model.StartsWith("Error") ? "danger" : "success";
    <div class="alert alert-@statusMessageClass alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @Model
    </div>
}

Views/Shared/_TutorsPartial.cshtml
<div class="instructors">
		<div class="instructors_background" style="background-image:url(lingua/images/instructors_background.png)"></div>
		<div class="container">
			<div class="row">
				<div class="col">
					<h2 class="section_title text-center">The Best Tutors in Town</h2>
				</div>
			</div>
			<div class="row instructors_row">

				<!-- Instructor -->
				<div class="col-lg-4 instructor_col">
					<div class="instructor text-center">
						<div class="instructor_image_container">
							<div class="instructor_image"><img src="lingua/images/Otacilio-foto-300x298.png" alt=""></div>
						</div>
						<div class="instructor_name"><a href="lingua/instructors.html">Otacílio José Moreira</a></div>
						<div class="instructor_title">Teacher</div>
						<div class="instructor_text">
							<p>MBA Logística e Gestão da Cadeia de Suprimentos – UFF – MBA em Administração – Universidade de Buffalo – Nova York – EUA – Informações adicionais: http://lattes.cnpq.br/3629744821527772</p>
						</div>
						<div class="instructor_social">
							<ul>
								<li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
								<li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
								<li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
							</ul>
						</div>
					</div>
				</div>

				<!-- Instructor -->
				<div class="col-lg-4 instructor_col">
					<div class="instructor text-center">
						<div class="instructor_image_container">
							<div class="instructor_image"><img src="lingua/images/martius-foto2-261x300.jpg" alt=""></div>
						</div>
						<div class="instructor_name"><a href="lingua/instructors.html">Martius Vicente</a></div>
						<div class="instructor_title">Teacher</div>
						<div class="instructor_text">
							<p>MBA Logística e Gestão da Cadeia de Suprimentos – UFF – Pós-doutorado pela UFRJ/Harvard Business School, MBA pelo MIT – Informações adicionais: http://lattes.cnpq.br/7037188590027119</p>
						</div>
						<div class="instructor_social">
							<ul>
								<li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
								<li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
								<li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
							</ul>
						</div>
					</div>
				</div>

				<!-- Instructor -->
				<div class="col-lg-4 instructor_col">
					<div class="instructor text-center">
						<div class="instructor_image_container">
							<div class="instructor_image"><img src="lingua/images/instructor_3.jpg" alt=""></div>
						</div>
						<div class="instructor_name"><a href="lingua/instructors.html">Sarah Parker</a></div>
						<div class="instructor_title">Teacher</div>
						<div class="instructor_text">
							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce enim nulla, mollis eu metus in, sagittis fringilla tortor.</p>
						</div>
						<div class="instructor_social">
							<ul>
								<li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
								<li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
								<li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
							</ul>
						</div>
					</div>
				</div>

			</div>
		</div>
	</div>