Models/Questao.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Simulacao.Models
{
    [Table("questao")]
    public class Questao {
        [Key, Column("idquestao")]
        public long idQuestao { get; set; }
        [Required]
        [Column("questao")]
        [Display(Name = "Question")]
        public string Pergunta { get; set; }
        [Required]
        [Column("idsubarea")]
        public int idSubarea { get; set; }
        [Column("idarea")]
        public int idArea { get; set; }
    }
}

Models/QuestaoViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Simulacao.Models {
    public class QuestaoViewModel {
        public Course Course { get; set; }
        public Area Area { get; set; }
        public Subarea Subarea { get; set; }
        public Questao Questao { get; set; }
        public List<Resposta> Respostas { get; set; }
        public string StatusMessage { get; set; }
    }
}

Controllers/QuestaoController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Simulacao.Data;
using Simulacao.Models;
using System.Linq;
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Options;

namespace Simulacao.Controllers {
    public class QuestaoController : Controller {
        private readonly UserManager<ApplicationUser> _userManager;
        private ApplicationDbContext dbContext;
        public QuestaoController(UserManager<ApplicationUser> userManager) {
            _userManager = userManager;
            dbContext = ApplicationDbContextFactory.Create();
        }
        private Questao GetQuestao(long idQuestao) => dbContext.Questao.SingleOrDefault(q => q.idQuestao == idQuestao);
        private QuestaoViewModel GetQuestaoViewModel(long idQuestao) {
            long idSubarea = dbContext.Questao.SingleOrDefault(q => q.idQuestao == idQuestao).idSubarea;
            long idArea = dbContext.Subarea.SingleOrDefault(s => s.idSubarea == idSubarea).idArea;
            long idCourse = dbContext.Area.SingleOrDefault(a => a.idArea == idArea).idCourse;
            QuestaoViewModel qvm = preencherQVM(idCourse, idSubarea);
            qvm.Questao = GetQuestao(idQuestao);
            qvm.Respostas = dbContext.Resposta.Where(r => r.idQuestao == idQuestao).ToList();
            return qvm;
        }
        private QuestaoViewModel preencherQVM(long idCourse, long idSubarea) {
            QuestaoViewModel qvm = new QuestaoViewModel();
            qvm.Course = dbContext.Course.SingleOrDefault(q => q.idCourse == idCourse);
            qvm.Subarea = dbContext.Subarea.SingleOrDefault(s => s.idSubarea == idSubarea);
            long idArea = dbContext.Subarea.SingleOrDefault(s => s.idSubarea == idSubarea).idArea;
            qvm.Area = dbContext.Area.SingleOrDefault(a => a.idArea == idArea);
            return qvm;
        }
        private CoursesViewModel preencherCVM() {
            CoursesViewModel cvm = new CoursesViewModel();
            cvm.Courses = dbContext.Course.ToList();
            cvm.Areas = dbContext.Area.ToList();
            cvm.Subareas = dbContext.Subarea.ToList();
            return cvm;
        }
        public JsonResult filtrarSubareas(long idArea) {
            IEnumerable<Subarea> subareas;
            if (idArea != 0) {
                subareas = dbContext.Subarea.Where(s => s.idArea == idArea).ToList();
            } else {
                subareas = dbContext.Subarea.ToList();
            }
            return Json(new SelectList(subareas, "idSubarea", "NomeSubarea"));
        }
        public JsonResult filtrarAreas(long idCourse) {
            IEnumerable<Area> areas;
            if (idCourse != 0) {
                areas = dbContext.Area.Where(s => s.idCourse == idCourse).ToList();
            } else {
                areas = dbContext.Area.ToList();
            }
            return Json(new SelectList(areas, "idArea", "NomeArea"));
        }
        public ActionResult PerguntasArea() {
            CoursesViewModel cvm = preencherCVM();
            return View(cvm);
        }
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> listarPerguntas(long idCourse, long idSubarea) {
            var roles = _userManager.GetRolesAsync(await _userManager.GetUserAsync(User));
            Course alvo = dbContext.Course.SingleOrDefault(c => c.idCourse ==idCourse);
            List<Questao> questoes = new List<Questao>();
            if (idCourse != 0) {
                foreach (var role in await roles) {
                    if (idCourse.ToString() == role) {
                        questoes = dbContext.Questao.Where(q => q.idSubarea == idSubarea).ToList();
                        ViewData["idSubarea"] = idSubarea;
                        ViewData["idCourse"] = idCourse;
                        return View("Questoes", questoes);
                    }
                }
            }
            ViewData["Erro"] = "You are not allowed to access the questions.";
            return View("PerguntasArea", preencherCVM());
        }

        [Authorize(Roles = "Admin")]
        public ActionResult VerDetalhes(long idQuestao) {
            return View("VerDetalhes", GetQuestaoViewModel(idQuestao));
        }
        [Authorize(Roles = "Admin")]
        public ActionResult inserirPergunta(long idCourse, long idSubarea) {
            return View("Inserir", preencherQVM(idCourse, idSubarea));
        }
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> CriarQuestao(Questao questao) {
            long idCourse = dbContext.Area.SingleOrDefault(a => a.idArea == questao.idArea).idCourse;
            if (ModelState.IsValid) {
                dbContext.Questao.Add(questao);
                await dbContext.SaveChangesAsync();
                return RedirectToAction(nameof(listarPerguntas), new {idCourse = idCourse, idSubarea = questao.idSubarea});
            }
            return View("Inserir", preencherQVM(idCourse, questao.idSubarea));
        }
        [Authorize(Roles = "Admin")]
        public ActionResult GetQuestaoToUpdate(long idQuestao, string StatusMessage = ""){
            QuestaoViewModel qvm = GetQuestaoViewModel(idQuestao);
            qvm.StatusMessage = StatusMessage;
            if(qvm.Questao != null) {
                return View("Editar", qvm);
            } else {
                return View("Error");
            }
        }
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> UpdateQuestao(Questao questao){
            var alvo = GetQuestao(questao.idQuestao);
            if(alvo != null && ModelState.IsValid) {
                dbContext.Entry(alvo).CurrentValues.SetValues(questao);
                await dbContext.SaveChangesAsync();
                return RedirectToAction(nameof(GetQuestaoToUpdate), new {idQuestao = questao.idQuestao, StatusMessage = "The question has been updated."});
            } else {
                return View("Editar", GetQuestaoViewModel(questao.idQuestao));
            }
        }
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> DeletarQuestao(long idQuestao){
            var alvo = GetQuestao(idQuestao);
            List<Resposta> respostas = dbContext.Resposta.Where(r => r.idQuestao == idQuestao).ToList();
            if(alvo != null){
                if (respostas != null) {
                    foreach (var resposta in respostas) {
                        dbContext.Resposta.Remove(resposta);
                    }
                }
                dbContext.Questao.Remove(alvo);
                await dbContext.SaveChangesAsync();
                long idArea = dbContext.Subarea.SingleOrDefault(s => s.idSubarea == alvo.idSubarea).idArea;
                long idCourse = dbContext.Area.SingleOrDefault(a => a.idArea == idArea).idCourse;
                return RedirectToAction(nameof(listarPerguntas), new {idCourse = idCourse, idSubarea = alvo.idSubarea});
            }else{
                return View("Error");
            }
        }
    }
}

Views/Questao/Editar.cshtml
@model Simulacao.Models.QuestaoViewModel

@await Html.PartialAsync("_StatusMessage", Model.StatusMessage)
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                @Html.ActionLink("Back", "listarPerguntas", "Questao", new {idCourse = @Model.Course.idCourse, idSubarea = @Model.Questao.idSubarea}, new { @class="btn btn-default"})
                <p></p>
                @using (Html.BeginForm("UpdateQuestao", "Questao", FormMethod.Post, new { @class = "form-horizontal form-material", role = "form" })) {
                    <div asp-validation-summary="All" class="text-danger"></div>
                    @Html.HiddenFor(q => q.Questao.idQuestao)
                    @Html.HiddenFor(q => q.Questao.idArea)
                    @Html.HiddenFor(q => q.Questao.idSubarea)
                    <div class="form-group">
                        <label class="col-md-12">Course</label>
                        <div class="col-md-12">
                            <input type="text" placeholder="@Model.Course.CourseName" class="form-control form-control-line" disabled>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-12">Area</label>
                        <div class="col-md-12">
                            <input type="text" placeholder="@Model.Area.NomeArea" class="form-control form-control-line" disabled>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-12">Subarea</label>
                        <div class="col-md-12">
                            <input type="text" placeholder="@Model.Subarea.NomeSubarea" class="form-control form-control-line" disabled>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-12" asp-for="Questao.Pergunta"></label>
                        <div class="col-md-12">
                            <input asp-for="Questao.Pergunta" type="text" class="form-control form-control-line">
                            <span asp-validation-for="Questao.Pergunta" class="text-danger"></span>
                        </div>
                    </div>
                    <button onclick="return confirm('Are you sure you want to update the question?');" type="submit" class="btn btn-success"> <i class="fa fa-check"></i> Save</button>
                    <p></p>
                    <a href="@Url.Action("inserirResposta", "Resposta", new {idQuestao = @Model.Questao.idQuestao})" type="button" class="btn btn-info"><i class="fa fa-plus-circle"></i> Add Answer</a>
                    <p></p>
                    <table class="table table-bordered table-striped" align="center">
                        <tr class="tb-titulo-azul-branco text-center"><th colspan="4">Answers</th></tr>
                        @foreach (var resposta in this.Model.Respostas) {
                            <tr>
                                <td style="background-color: white">@resposta.NomeResposta</td>
                                <td style="background-color: white" class="text-center">@Html.ActionLink("Ver Detalhes", "VerResposta", "Resposta", new { idResposta = @resposta.idResposta}, new { @class="btn btn-primary"})</td>
                                <td style="background-color: white" class="text-center">@Html.ActionLink("Editar", "GetRespostaToUpdate", "Resposta", new { idResposta = @resposta.idResposta}, new { @class="btn btn-warning"})</td>
                                <td style="background-color: white" class="text-center">@Html.ActionLink("Excluir", "DeletarResposta", "Resposta", new { idResposta = @resposta.idResposta}, new { @class="btn btn-danger", onclick="return confirm('Tem certeza que deseja excluir a resposta?');"})</td>
                            </tr>
                        }
                    </table>
                }
            </div>
        </div>
    </div>
</div>

Views/Questao/Inserir.cshtml
@model QuestaoViewModel

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                @Html.ActionLink("Back", "listarPerguntas", "Questao", new {idCourse = @Model.Course.idCourse, idSubarea = @Model.Subarea.idSubarea}, new { @class="btn btn-default"})
                <p></p>
                @using (Html.BeginForm("CriarQuestao", "Questao", FormMethod.Post, new { @class = "form-horizontal form-material", role = "form" })) {
                    <div asp-validation-summary="All" class="text-danger"></div>
                    @Html.Hidden("idArea", @Model.Area.idArea)
                    @Html.Hidden("idSubarea", @Model.Subarea.idSubarea)
                    <div class="form-group">
                        <label class="col-md-12">Course</label>
                        <div class="col-md-12">
                            <input type="text" placeholder="@Model.Course.CourseName" class="form-control form-control-line" disabled>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-12">Area</label>
                        <div class="col-md-12">
                            <input type="text" placeholder="@Model.Area.NomeArea" class="form-control form-control-line" disabled>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-12">Subarea</label>
                        <div class="col-md-12">
                            <input type="text" placeholder="@Model.Subarea.NomeSubarea" class="form-control form-control-line" disabled>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-12" asp-for="Questao.Pergunta"></label>
                        <div class="col-md-12">
                            <input asp-for="Questao.Pergunta" id="Pergunta" name="Pergunta" type="text" class="form-control form-control-line">
                            <span asp-validation-for="Questao.Pergunta" class="text-danger"></span>
                        </div>
                    </div>
                    <input onclick="return confirm('Are you sure you want to insert a new question?');" class="btn btn-info" type="submit" value="Add Question"/>
                }
            </div>
        </div>
    </div>
</div>

Views/Questao/PerguntasArea.cshtml
@model CoursesViewModel
@{
    <script>
        function filtrarAreas(obj) {;              
            $.ajax({  
                type: 'POST',  
                url: '@Url.Action("filtrarAreas", "Questao")',
                async: false,
                dataType: 'json',
                data: { idCourse: obj.value },  
                success: function (areas) {
                    $("#idArea").empty();
                    $("#idArea").append('<option value="0">Choose an area</option>');
                    $.each(areas, function (i, area) {
                        $("#idArea").append('<option value="' + area.value + '">' + area.text + '</option>');  
                    });
                    $("#btnEditQuestion").attr('disabled', 'true');
                },  
                error: function (ex) {
                    alert('Failed to retrieve areas.' + ex);  
                }  
            });  
            return false; 
        }
        function filtrarSubareas(obj) {;              
            $.ajax({  
                type: 'POST',  
                url: '@Url.Action("filtrarSubareas", "Questao")',
                async: false,
                dataType: 'json',
                data: { idArea: obj.value },  
                success: function (subareas) {
                    if (obj.value != 0) {
                        $("#btnEditQuestion").removeAttr('disabled');
                        $("#idSubarea").empty();
                        $.each(subareas, function (i, subarea) {
                            $("#idSubarea").append('<option value="' + subarea.value + '">' + subarea.text + '</option>');  
                        });
                    } else {
                        $("#btnEditQuestion").attr('disabled', 'true');
                    }
                },  
                error: function (ex) {
                    alert('Failed to retrieve areas.' + ex);  
                }  
            });  
            return false; 
        }
    </script>
}
<html>
    <body>
        <div class="col-12">
		    <div class="card">
			    <div class="card-body">
                    @Html.ActionLink("Back", "Dashboard", "Home", new {}, new { @class="btn btn-default"})
                    <p></p>
                    @using (Html.BeginForm("listarPerguntas", "Questao", FormMethod.Post, new { @class = "form-horizontal form-material", role = "form", enctype = "multipart/form-data"})) {
                    <div asp-validation-summary="All" class="text-danger"></div>
                    <p style="color:red;">@ViewData["Erro"]</p>
                    <div class="form-group">
                        <label class="col-md-12">Course</label>
                        <div class="col-md-12">
                            @Html.DropDownList("idCourse", new SelectList(@Model.Courses, "idCourse", "CourseName"), "Choose a course", new {@class="form-control", @onchange="filtrarAreas(this)"})
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-12">Area</label>
                        <div class="col-md-12">
                            @Html.DropDownList("idArea", new SelectList(@Model.Areas, "idArea", "NomeArea"), "Choose an area", new {@class="form-control", @onchange="filtrarSubareas(this)"})
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-12">Subarea</label>
                        <div class="col-md-12">
                            @Html.DropDownList("idSubarea", new SelectList(@Model.Subareas, "idSubarea", "NomeSubarea"), "Choose a subarea", new {@class="form-control"})
                        </div>
                    </div>
                    <input id="btnEditQuestion" class="btn btn-primary" type="submit" value="Edit questions" disabled/>
                    }
                </div>
            </div>
        </div>
    </body>
</html>

Views/Questao/Questoes.cshtml
@model List<Simulacao.Models.Questao>
<html>
    <body>
        <div class="row page-titles">
            <div class="col-md-5 align-self-center">
                <h4 class="text-themecolor">Questions</h4>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        @Html.ActionLink("Back", "PerguntasArea", "Questao", new {}, new { @class="btn btn-default"}) <a href="@Url.Action("inserirPergunta", "Questao", new {idCourse = @ViewData["idCourse"], idSubarea = @ViewData["idSubarea"]})" type="button" class="btn btn-info"><i class="fa fa-plus-circle"></i> Add Question</a>
                        <p></p>
                        <table class="table table-bordered table-striped table-hover">
                            <tr class="text-nowrap tb-titulo-azul-branco">
                                <th class="text-center" colspan="4">Questions</th>
                            </tr>
                            @foreach (var questao in this.Model) {
                                <tr class="text-nowrap tb-linha-fundo">
                                    <col width="100%">
                                    <td style="background-color: white">@questao.Pergunta</td>
                                    <td class="text-center" style="background-color: white">@Html.ActionLink("See Details", "VerDetalhes", new { idQuestao = @questao.idQuestao}, new { @class="btn btn-primary"})</td>
                                    <td class="text-center" style="background-color: white">@Html.ActionLink("Edit", "GetQuestaoToUpdate", new { idQuestao = @questao.idQuestao}, new { @class="btn btn-warning"})</td>
                                    <td class="text-center" style="background-color: white">@Html.ActionLink("Delete", "DeletarQuestao", new { idQuestao = @questao.idQuestao}, new { @class="btn btn-danger", onclick="return confirm('Are you sure you want to delete the question?');"})</td>
                                </tr>
                            }
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

Views/Questao/VerDetalhes.cshtml
@model Simulacao.Models.QuestaoViewModel
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                @Html.ActionLink("Back", "listarPerguntas", "Questao", new {idCourse = @Model.Course.idCourse, idSubarea = @Model.Subarea.idSubarea}, new { @class="btn btn-default"})
                <p></p>
                <div class = "form-horizontal form-material">
                    <div class="form-group">
                        <label class="col-md-12">Area</label>
                        <div class="col-md-12">
                            <input value="@Model.Area.NomeArea" type="text" class="form-control form-control-line" disabled>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-12">Subarea</label>
                        <div class="col-md-12">
                            <input value="@Model.Subarea.NomeSubarea" type="text" class="form-control form-control-line" disabled>
                        </div>
                    </div>
                </div>
                <table class="table table-bordered" align="center">
                    <tr class="tb-titulo-azul-branco"><td colspan="3">@Html.Label("Question: ") @Model.Questao.Pergunta</td></tr>
                    <tr>
                        <td>@Html.Label("Answer")</td>
                        <td>@Html.Label("Correct?")</td>
                        <td>@Html.Label("Explanation")</td>
                    </tr>
                    @foreach (var resposta in this.Model.Respostas) {
                        <tr>
                            <td>@resposta.NomeResposta</td>
                            <td>@resposta.Correta</td>
                            <td>@resposta.Explicacao</td>
                        </tr>
                    }
                </table>
            </div>
        </div>
    </div>
</div>