Models/Course/CourseInfoViewModel.cs
using System.Collections.Generic;

namespace Simulacao.Models {
    public class CourseInfoViewModel {
        public Course Course { get; set; }
        public List<Area> Areas { get; set; }
        public List<Subarea> Subareas { get; set; }
        public List<PaginatedSubarea> PaginatedSubareas { get; set; }
        public List<MaterialEstudo> Coursewares { get; set; }
        public string StatusMessage { get; set; }
        public string imgSrc { get; set; }
    }
}

Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Simulacao.Data;
using Simulacao.Models;

namespace Simulacao.Controllers
{
    public class CourseController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private ApplicationDbContext dbContext;
        public CourseController(UserManager<ApplicationUser> userManager) {
            _userManager = userManager;
            dbContext = ApplicationDbContextFactory.Create();
        }

        public IActionResult Index() {
            List<CourseViewModel> cvms = new List<CourseViewModel>();
            foreach (var course in dbContext.Course.ToList()) {
                var UserId = _userManager.GetUserId(User);
                List<Enrollment> enrollments = dbContext.Enrollment.Where(e => e.UserId == UserId).ToList();
                bool enrolledCourse = false;
                foreach (var enrolled in enrollments) {
                    if (course.idCourse == enrolled.idCourse) {enrolledCourse = true;} else {enrolledCourse = false;}
                }
                if (enrolledCourse == false) {
                    CourseViewModel model = new CourseViewModel();
                    model.idCourse = course.idCourse;
                    model.CourseName = course.CourseName;
                    model.ProfessorName = course.ProfessorName;
                    model.About = course.About;
                    if (course.Image != null) {
                        var base64 = Convert.ToBase64String(course.Image);
                        model.imgSrc = String.Format("data:image/jpg;base64,{0}", base64);
                    }
                    cvms.Add(model);
                }
            }
            return View(cvms);
        }

        public IActionResult CourseInfo(long idCourse) {
            CourseInfoViewModel civm = new CourseInfoViewModel();
            civm.Course = dbContext.Course.SingleOrDefault(c => c.idCourse ==idCourse);
            civm.Areas = dbContext.Area.Where(c => c.idCourse == idCourse).ToList();
            civm.Subareas = new List<Subarea>();
            foreach (var area in civm.Areas) {
                List<Subarea> subareas = dbContext.Subarea.Where(s => s.idArea == area.idArea).ToList();
                foreach (var subarea in subareas) {
                    civm.Subareas.Add(subarea);
                }
            }
            if (civm.Course.Image != null) {
                var base64 = Convert.ToBase64String(civm.Course.Image);
                civm.imgSrc = String.Format("data:image/jpg;base64,{0}", base64);
            }
            return View(civm);
        }

        //--------------------------------------------------------------------
        //Parte de administração do curso
        //--------------------------------------------------------------------
        [Authorize(Roles = "Admin")]
        public ActionResult listarCursos() {
            return View("Courses", dbContext.Course.ToList());
        }

        [Authorize(Roles = "Admin")]
        public ActionResult inserirCurso() {
            return View();
        }

        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> CriarCurso(Course course, IFormFile coursephoto) {
            if (coursephoto == null || course.CourseName == null || course.ProfessorName == null || course.About == null || course.Price == null) {
                return View("inserirCurso");
            }
            using (var ms = new System.IO.MemoryStream()) {
                await coursephoto.CopyToAsync(ms);
                course.Image = ms.ToArray();
                await dbContext.Course.AddAsync(course);
                await dbContext.SaveChangesAsync();
                return RedirectToAction(nameof(listarCursos));
            }
        }

        private CourseInfoViewModel GetCourseInfoViewModel(long idCourse) {
            CourseInfoViewModel civm = new CourseInfoViewModel();
            civm.Course = dbContext.Course.SingleOrDefault(c => c.idCourse == idCourse);
            civm.Areas = dbContext.Area.Where(a => a.idCourse == idCourse).ToList();
            return civm;
        }

        [Authorize(Roles = "Admin")]
        public ActionResult GetCourseToUpdate(int idCourse, string StatusMessage = "") {
            CourseInfoViewModel civm = GetCourseInfoViewModel(idCourse);
            if (civm != null) {
                if (civm.Course.Image != null) {
                    var base64 = Convert.ToBase64String(civm.Course.Image);
                    civm.imgSrc = String.Format("data:image/jpg;base64,{0}", base64);
                }
                civm.StatusMessage = StatusMessage;
                return View("Editar", civm);
            } else {
                return View("Error");
            }
        }
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> UpdateCourse(Course course, IFormFile coursephoto) {
            var alvo = dbContext.Course.SingleOrDefault(c => c.idCourse == course.idCourse);
            if(alvo != null) {
                if ((alvo.Image == null && coursephoto == null) || course.CourseName == null || course.ProfessorName == null || course.About == null || course.Price == null) {
                    return View("Editar", GetCourseInfoViewModel(course.idCourse));
                }
            }

            if (course.CourseName != alvo.CourseName) {
                dbContext.Entry(alvo).Property("CourseName").CurrentValue = course.CourseName;
                await dbContext.SaveChangesAsync();
            }

            if (course.ProfessorName != alvo.ProfessorName) {
                dbContext.Entry(alvo).Property("ProfessorName").CurrentValue = course.ProfessorName;
                await dbContext.SaveChangesAsync();
            }

            if (course.Price != alvo.Price) {
                dbContext.Entry(alvo).Property("Price").CurrentValue = course.Price;
                await dbContext.SaveChangesAsync();
            }

            if (course.About != alvo.About) {
                dbContext.Entry(alvo).Property("About").CurrentValue = course.About;
                await dbContext.SaveChangesAsync();
            }

            if (coursephoto != null) {
                using (var ms = new System.IO.MemoryStream()) {
                    await coursephoto.CopyToAsync(ms);
                    dbContext.Entry(alvo).Property("Image").CurrentValue = ms.ToArray();
                    await dbContext.SaveChangesAsync();
                }
            }
            return RedirectToAction(nameof(GetCourseToUpdate), new {idCourse = alvo.idCourse, StatusMessage = "The course has been updated."});
        }

        [Authorize(Roles = "Developer")]
        public async Task<ActionResult> DeletarCurso(int idCourse) {
            var alvo = dbContext.Course.SingleOrDefault(c => c.idCourse == idCourse);
            IdentityRole targetRole = dbContext.Roles.SingleOrDefault(r => r.Name == idCourse.ToString());
            if(alvo != null){
                foreach (var area in dbContext.Area.ToList()) {
                    foreach (var subarea in dbContext.Subarea.ToList()) {
                        if (area.idArea == subarea.idArea) {
                            foreach (var material in dbContext.MaterialEstudo.ToList()) {
                                if (material.idSubarea == subarea.idSubarea) {
                                    dbContext.MaterialEstudo.Remove(material);
                                }
                            }
                            foreach (var questao in dbContext.Questao.ToList()) {
                                if (questao.idSubarea == subarea.idSubarea) {
                                    foreach (var resposta in dbContext.Resposta.ToList()) {
                                        if (resposta.idQuestao == questao.idQuestao) {
                                            dbContext.Resposta.Remove(resposta);
                                        }
                                    }
                                    dbContext.Questao.Remove(questao);
                                }
                            }
                            dbContext.Subarea.Remove(subarea);
                        }
                    }
                    dbContext.Area.Remove(area);
                }
                if (targetRole != null) {
                    dbContext.Roles.Remove(targetRole);
                }
                dbContext.Course.Remove(alvo);
                await dbContext.SaveChangesAsync();
                return RedirectToAction(nameof(listarCursos));
            }else{
                return View("Error");
            }
        }
    }
}

Controllers/EnrollmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Simulacao.Data;
using Simulacao.Models;

namespace Simulacao.Controllers
{
    public class EnrollmentController : Controller {
        private readonly UserManager<ApplicationUser> _userManager;
        private ApplicationDbContext dbContext;
        public EnrollmentController(UserManager<ApplicationUser> userManager) {
            _userManager = userManager;
            dbContext = ApplicationDbContextFactory.Create();
        }
        private CategoryViewModel GetCategoryViewModel(long idSubarea){
            CategoryViewModel cvm = new CategoryViewModel();
            cvm.Category = dbContext.Category.SingleOrDefault(c => c.idSubarea == idSubarea);
            cvm.Topics = dbContext.Topic.Where(t => t.idCategory == cvm.Category.idCategory).ToList();
            cvm.Postings = new List<PostingViewModel>();
            string photo = "../images/blank-profile-picture.png";
            ApplicationUser user = new ApplicationUser();
            foreach (var topic in cvm.Topics) {
                user = dbContext.ApplicationUser.SingleOrDefault(u => u.Id == topic.idUser);
                if (user.UserPhoto != null) {
                    var base64 = Convert.ToBase64String(user.UserPhoto);
                    photo = String.Format("data:image/jpg;base64,{0}", base64);
                }
                ViewData["imgUserTopic"] = photo;
                List<Posting> postings = dbContext.Posting.Where(p => p.idTopic == topic.idTopic).ToList();
                foreach (var post in postings) {
                    photo = "../images/blank-profile-picture.png";
                    user = dbContext.ApplicationUser.SingleOrDefault(u => u.Id == post.idUser);
                    if (user.UserPhoto != null) {
                        var base64 = Convert.ToBase64String(user.UserPhoto);
                        photo = String.Format("data:image/jpg;base64,{0}", base64);
                    }
                    PostingViewModel postingTarget = new PostingViewModel{
                        idTopic = post.idTopic,
                        idPosting = post.idPosting,
                        idUser = post.idUser,
                        Message = post.Message,
                        imgSrc = photo
                    };
                    cvm.Postings.Add(postingTarget);
                }
            }
            return cvm;
        }
        
        private async Task<StepCourseViewModel> selecionarMaterialDidatico(int? page, long? idCourse) {
            StepCourseViewModel scvm = new StepCourseViewModel();
            scvm.Course = dbContext.Course.SingleOrDefault(c => c.idCourse == idCourse);
            IQueryable<Subarea> subareas = from s in dbContext.Subarea where s.idArea == 0 select s;
            foreach (var area in await dbContext.Area.Where(a => a.idCourse == idCourse).ToListAsync()) {
                subareas = (from s in dbContext.Subarea where s.idArea == area.idArea select s).Concat(subareas);
            }
            scvm.Subareas = await PaginatedList<Subarea>.CreateAsync(subareas.OrderBy(s => s.idArea), page ?? 1, 1);
            scvm.Area = dbContext.Area.SingleOrDefault(a => a.idArea == scvm.Subareas.First().idArea);
            scvm.StudyMaterials = dbContext.MaterialEstudo.Where(m => m.idSubarea == scvm.Subareas.First().idSubarea).OrderBy(m => m.Ordem).ToList();
            return scvm;
        }

        public IActionResult Index() {
            EnrollmentViewModel evm = new EnrollmentViewModel();
            List<CourseViewModel> cvms = new List<CourseViewModel>();
            List<Enrollment> enrollments = dbContext.Enrollment.Where(e => e.UserId == _userManager.GetUserId(User)).ToList();
            foreach (var enrollment in enrollments)
            {
                Course course = dbContext.Course.SingleOrDefault(c => c.idCourse == enrollment.idCourse);
                CourseViewModel cvm = new CourseViewModel {
                    idCourse = course.idCourse,
                    CourseName = course.CourseName,
                    ProfessorName = course.ProfessorName,
                    About = course.About,
                    Price = course.Price
                };
                if (course.Image != null) {
                    var base64 = Convert.ToBase64String(course.Image);
                    cvm.imgSrc = String.Format("data:image/jpg;base64,{0}", base64);
                }
                cvms.Add(cvm);
            }
            if (cvms != null) {
                evm.Courses = cvms;
            }
            if (evm.Courses == null) {
                ViewData["NenhumCurso"] = "1";
            }
            return View("MyCourses", evm);
        }

        public async Task<IActionResult> Enroll(long idCourse) {
            if (ModelState.IsValid) {
                Enrollment enrollment = new Enrollment {
                    UserId = _userManager.GetUserId(User),
                    idCourse = idCourse,
                    RegisterDate = DateTime.Today
                };
                dbContext.Enrollment.Add(enrollment);
                await dbContext.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return RedirectToRoute( new {
                controller = "Course",
                action = "listarCursos"
            });
        }

        public IActionResult StartCourse(long idCourse) {
            CourseInfoViewModel civm = new CourseInfoViewModel();
            civm.Course = dbContext.Course.SingleOrDefault(c => c.idCourse ==idCourse);
            civm.Areas = dbContext.Area.Where(c => c.idCourse == idCourse).ToList();
            civm.PaginatedSubareas = new List<PaginatedSubarea>();
            civm.Coursewares = new List<MaterialEstudo>();
            int i = 1;
            foreach (var area in civm.Areas) {
                List<Subarea> subareas = dbContext.Subarea.Where(s => s.idArea == area.idArea).ToList();
                foreach (var subarea in subareas) {
                    PaginatedSubarea pagSubarea = new PaginatedSubarea{
                        idSubarea = subarea.idSubarea,
                        idArea = subarea.idArea,
                        NomeSubarea = subarea.NomeSubarea,
                        Page = i++
                    };
                    civm.PaginatedSubareas.Add(pagSubarea);
                    List<MaterialEstudo> materiais = dbContext.MaterialEstudo.Where(m => m.idSubarea == subarea.idSubarea).ToList();
                    foreach (var material in materiais) {
                        if (material != null) {
                            civm.Coursewares.Add(material);
                        }
                    }
                }
            }
            return View(civm);
        }

        public async Task<IActionResult> Course(long idCourse, int page = 1) {
            StepCourseViewModel scvm = await selecionarMaterialDidatico(page, idCourse);
            ViewData["idCourse"] = idCourse;
            ViewData["CourseName"] = dbContext.Course.SingleOrDefault(c => c.idCourse == idCourse).CourseName;
            return View(scvm);
        }

        public IActionResult Discussion(long idCourse) {
            return RedirectToRoute(new {
                controller = "Topic",
                action = "ListTopicsPerCategory",
                idCourse = idCourse
            });
        }
        public async Task<IActionResult> Unenroll(long idCourse) {
            var alvo = await dbContext.Enrollment.SingleOrDefaultAsync(e => e.idCourse == idCourse && e.UserId == _userManager.GetUserId(User));
            if(alvo != null && ModelState.IsValid) {
                dbContext.Enrollment.Remove(alvo);
                await dbContext.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

Views/Enrollment/Course.cshtml
@model StepCourseViewModel

@await Html.PartialAsync("_CourseSteps")

Views/Enrollment/MyCourses.cshtml
@if (@ViewData["NenhumCurso"] == "1") {    
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">You are not enrolled in any courses.</h5>
        </div>
    </div>
} else {
    <div class="card">
        <div class="card-body p-b-0">
            <ul class="nav nav-tabs customtab2" role="tablist">
                <li class="nav-item"> <a class="nav-link active" data-toggle="tab" href="#mycourses" role="tab"><span class="hidden-sm-up"><i class="ti-book"></i></span> <span class="hidden-xs-down">My Courses</span></a> </li>
                <li class="nav-item"> <a class="nav-link" data-toggle="tab" href="#simulateds" role="tab"><span class="hidden-sm-up"><i class="ti-user"></i></span> <span class="hidden-xs-down">My Simulateds</span></a> </li>
                <li class="nav-item"> <a class="nav-link" data-toggle="tab" href="#exams" role="tab"><span class="hidden-sm-up"><i class="ti-email"></i></span> <span class="hidden-xs-down">My Exams</span></a> </li>
            </ul>
            <!-- Tab panes -->
            <div class="tab-content">
                <div class="tab-pane active" id="mycourses" role="tabpanel">
                    <div class="p-20">
                        @await Html.PartialAsync("_MyCoursesPartial")
                    </div>
                </div>
                <div class="tab-pane  p-20" id="simulateds" role="tabpanel">
                    @await Html.PartialAsync("_MySimulateds")
                </div>
                <div class="tab-pane p-20" id="exams" role="tabpanel">
                    @await Html.PartialAsync("_MyExams")
                </div>
            </div>
        </div>
    </div>
}

Views/Enrollment/StartCourse.cshtml
@model CourseInfoViewModel

@inject UserManager<ApplicationUser> UserManager
@{ int page = 0; }
<div class="row page-titles">
    <div class="col-md-5 align-self-center">
        <h4 class="text-themecolor">Start Course</h4>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-xs-12">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-3 border-right"> <strong>Course Name</strong>
                        <br>
                        <p class="text-muted">@Html.DisplayFor(c => c.Course.CourseName)</p>
                    </div>
                    <div class="col-md-3 border-right"> <strong>Course Price</strong>
                        <br>
                        <p class="text-muted">@Html.DisplayFor(c => c.Course.Price)</p>
                    </div>
                    <div class="col-md-3 border-right"> <strong>Professor Name</strong>
                        <br>
                        <p class="text-muted">@Html.DisplayFor(c => c.Course.ProfessorName)</p>
                    </div>
                    <div class="col-md-3"> <strong>Difficulty</strong>
                        <br>
                        <p class="text-muted">Advanced</p>
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-md-12">
                        <p>@Html.Raw(@Model.Course.About)</p>
                    </div>
                </div>
                <hr>
                <div class="row p-b-15">
                    <div class="col-md-12">
                        @foreach (var area in this.Model.Areas) {
                        <div id="accordion1" role="tablist" aria-multiselectable="true">
                            <div class="card m-b-0">
                                <div class="card-header" role="tab" id="headingOne1">
                                    <h5 class="mb-0">
                                    <a class="link" data-toggle="collapse" data-parent="#accordion1" href="#@area.idArea" aria-expanded="true" aria-controls="collapseOne">
                                        @area.NomeArea
                                    </a>
                                    </h5>
                                </div>
                                <div id="@area.idArea" class="collapse show" role="tabpanel" aria-labelledby="headingOne1">
                                    <div class="card-body">
                                        <ul class="list-icons">
                                        @foreach (var subarea in this.Model.PaginatedSubareas) {
                                            if (@area.idArea == @subarea.idArea) {
                                                <li>@Html.ActionLink(@subarea.NomeSubarea, "Course", "Enrollment", new {idCourse = @area.idCourse, page = @subarea.Page})</li>
                                            }
                                        }
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                        }
                    </div>
                </div>
                <hr>
                <div class="row text-center p-10">
                    @Html.ActionLink("Start Course", "Course", "Enrollment", new {idCourse = @Model.Areas[0].idCourse}, new { @class="btn btn-info btn-lg"})
                </div>
            </div>
        </div>
    </div>
</div>